### ISSUE TITLE
No option to enter Manifest ID during Custom deployment

### ISSUE THREAD

**Issue by Snowfox05** [OfficeDev/microsoft-teams-apps-greatideas#6]
Step 2 point 6 d. references a Manifest ID, however during the custom deployment in Azure there isn't an field to enter this data into.

Thanks

**Comment by gmccollin** [comment]
Followed the instructions to the letter (also agree with Snowfox05 comment). Able to install the app in Teams but when going to "Great Ideas" tab get the following message. 

**_"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable"_**

![image](https://user-images.githubusercontent.com/45073773/87455155-e7d2be00-c5fc-11ea-919b-0db0127aaf0d.png)

**Comment by abbodh** [comment]
Hi @Snowfox05 @gmccollin - sorry to hear about the issue you faced. The manifest id is not required, and the deployment guide is updated in order to reflect the same. 

@gmccollin - the error you see seems to be generic and could be due to misconfiguration in manifest file. Can you please check and confirm the static tab URL.

**Comment by gmccollin** [comment]
Thanks for coming back to me, the static tab URL is 

            "contentUrl": "https://GreatIdeas.azurefd.net/ideas",

**Comment by abbodh** [comment]
Hi @gmccollin - thanks for letting know. Can you send a screenshot of the resources created to confirm that 'GreatIdeas' resources created correctly. Also, can you confirm if the app service is running.

**Comment by abbodh** [comment]
Ohh... looks like there is a bug in the ARM deployment file. Can you please navigate to your Azure app services > Settings > Configuration > Application Settings > Advanced edit .

Can you please change 'App:TeamLink' key to 'App:CuratorTeamLink'. 

The fix is under review and should be merged soon #7

**Comment by gmccollin** [comment]
@abbodh, made the Azure app services change 
![image](https://user-images.githubusercontent.com/45073773/87780289-4e86f000-c826-11ea-8bf0-0438c97f0cc4.png)

but still no joy in fact now have a invalid URI 
![image](https://user-images.githubusercontent.com/45073773/87780337-6bbbbe80-c826-11ea-841f-bedb6acccbab.png)

Please also see resources created and the service is running
![image](https://user-images.githubusercontent.com/45073773/87780503-c523ed80-c826-11ea-9a74-29ceced3a918.png)

**Comment by gmccollin** [comment]
do you have any update? i have recreated all the steps again but still erroring. 

Does this work for other people or am i the first to try to install?

**Comment by abbodh** [comment]
Hi @gmccollin , I tried to perform the deployment again in a new test tenant and interestingly the build reported the npm error for app service. The fix is under review and will be merge soon with PR #7. 

Would it be possible for you to share the bug details. You can go to app service > deployment center and check whether the deployment succeeded. If shows as failed, please check the logs and share it. 

Apologize for the trouble.

**Comment by abbodh** [comment]
Hi @gmccollin - can you try to sync the latest changes to verify whether the build is succeeded or not. Please refer https://github.com/OfficeDev/microsoft-teams-apps-greatideas/wiki/Continuos-deployment#continuous-deployment-in-azure-app-services to leverage continuous deployment to upgrade the solution. 

Looking forward for the feedback.

**Comment by abbodh** [comment]
@gmccollin - let us know if the deployment succeeded. We have revised the deployment instructions for better clarity. Feel free to open a new issue if the problem still persists.

**Comment by laracloud123** [comment]
@abbodh have you fixed this issue? I still get the failure message: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." Thanks
